### ISSUE TITLE
架构设计

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#1]

**Comment by guoliu** [comment]
请问目前架构上有些什么计划呢？比如不同信息如何从收集、分析到呈现，是否固定依赖一个api，以及如何与其他前端联动等。有一点想法：

* 可视化框架可以用plotly，地图信息等组件也很全。可以免费host，然后前端通过iframe接入，与其他前端独立，可复用。
* 如果有数据分析志愿者，部分分析可以直接用notebook转html渲染出来，甚至直接用github的notebook渲染。
