### ISSUE TITLE
Map的信息应该由我们这边提供？

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#10]
我们现在的mock数据是：
```
{
  "name": "中国",
  "mapUrl": "https://map-1252957949.cos.ap-guangzhou.myqcloud.com/china.json",
  "data": [{...}]
}
```
因为map信息是static的（而且我们`map_data`里已经有了）而且不是信息组存入的，我们code里应该自己带 `地名->mapurl` 的信息，不应该要求调用组件的人提供。

之前slack有小伙伴提过：
```
我之前做的地图是这样的
市级查询经纬度
全国300多个城市
可以做一个表city.json {"武汉":[经度,维度],....}
县级查询经纬度
因为有很多重名的县
需要用身份证前6位做key
{430200:"长沙县",...}
{
  430200:[经度,维度]
  ....
}
```

**Comment by shadowings-zy** [comment]
这个问题是这样的哈，我当初设计的时候是觉得，调用组件的人可能不一定会用我们map_data里面的url，所以直接把url暴露出来作为参数让调用者自己传了。

如果我们能保证map_data里面的数据很完整、而且很准确的话，那我们自己做一下“地名->mapurl”逻辑也是可以的。

**Comment by tongshuangwu** [comment]
我觉得我们建一个逻辑，然后前端传入一个key即可，但是可以有optional map url把我们的overwrite掉以防万一？因为如果这个数据本身数据组没有去收集的话，相当于还得前端是搞一次，感觉可能没这个必要。
之前提供这个mapping的是 @birdsofsummer

**Comment by tongshuangwu** [comment]
已经顺便在 #27 中实现了。
