### ISSUE TITLE
偶尔点击virusMap的timeline右边virusCharts线会消失

### ISSUE THREAD

**Issue by Ritaotao** [wuhan2020/map-viz#100]
没有发现规律，大部分出现在autoplay on的时候随机点击timeline的某一天，会使右边图表完全变blank，如下图：
![image](https://user-images.githubusercontent.com/15093013/73600532-47418380-451f-11ea-9a75-51302c7710d4.png)

**Comment by shadowings-zy** [comment]
朋友，更新一下代码库再看看呢？我们在最新的代码库中对这个问题进行了修正
