### ISSUE TITLE
VirusMap的input数据格式？

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#11]
如果我们已经有了确认的数据格式（现在调用里有用到`confirmed`之类的），那`VirusMapProps`里data的类型就不能是`any[]`了。要把这个类型固定下来吗？
还是我们还是像之前说的，让调用的人来输入哪些key要作为encoding（比如现在图上的颜色 `colorKey="confirmed"`，还有hover `tooltipKey={"cured": 治愈，"death"：死亡}`）?
见数据格式设计的issue #3

**Comment by shadowings-zy** [comment]
这个我建议先直接在VirusMap组件中固定下来，我可以修改一下VirusMapProps里data的数据类型。
如果有更高级的定制需要的话，直接用EchartsMap二次开发就好了~

**Comment by shadowings-zy** [comment]
这个data类型的issue我来完善吧
