### ISSUE TITLE
确诊小区的可视化

### ISSUE THREAD

**Issue by Alexiaohei** [wuhan2020/map-viz#119]
**一、心里话**
各位大佬、前辈都有很强的技术实力，但一个很诚心的建议就是：项目本身的**方向问题**（可能这个得和产品组聊？），无论省级、县级还是市级颗粒度，本质上和看表格的差异不大，人们获得的信息就是“这个省、市、县有疫情XX起”，这和知乎、支付宝、微博、丁香医生的实时疫情**没有差异**。

**_那为什么民众要选择看我们的可视化项目，而不去看丁香、知乎、微博的实时疫情呢..._**

**二、确诊小区可视化案例**
抱歉自己无前端能力实现，不知道是否有大佬带（下面就是两个已经实现的例子）
1、量城科技确诊小区、场所可视化
[https://weibointl.api.weibo.cn/share/119707143.html?weibo_id=4468005620367302](url)
2、南都确诊小区、场所查询系统及可视化
[http://h5.oeeee.com/h5/v20/nCovcase/](url)
3、还有一些民间制图的，就不贴出来了。
**三、实现问题**
下面是我拿深圳数据做的，一句话讲就是获得地址数据、地址转坐标（地理编码）、可视化。我这里借用高德地图开放平台，而事实上南都也是这么搞的......
[https://maplab.amap.com/share/mapv/00f719ef8b882614314cb18e5480cf9b](url)
**四、数据来源**
以官方为准（如卫健委发布等，这点广东各城市卫健委均有披露地址数据）

疫情“高峰”将至，结合官方发布数据，真实的**确诊小区坐标**及**可缩放的、清晰的地图可视化**效果，将会给民众带来**差异化的**参考价值：
【1】这个确诊小区在哪里（具体位置）；
【2】离我家多远（直观认知）；
【3】我家周围有多少；
【4】......
工作原因，没有太深入了解项目，可能自己的理解以及自己提的这个想法也有不成熟的地方，还望指出，但真心想让大众看到并认可各位大佬的努力，共勉。

**Comment by tongshuangwu** [comment]
感谢提议！
1. 我们这个小项目的定位就是信息补全，它不是大项目的核心所在。所以虽然有做的比现在更精密的可能性(比如引入迁移数据或者与政策发布时间轴做对应)，我们实现它的目标只是能做到"我们有一个比人家数据稍微多一点的地图"。所以您说的没错，用户确实获得的信息就是哪哪哪有多少起，这也是最初的定位。

2. 千言万语归结于高精度信息缺省项太多，比如大部分城市都没有小区精度的分布信息。
