### ISSUE TITLE
与时间轴及其他信息的结合

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#13]
暂时仅限疫情地图：
画一个line chart/stacked area chart，横轴是时间纵轴 高度是 确诊/疑似/死亡 https://www.echartsjs.com/examples/zh/editor.html?c=area-stack，来看病毒进展（起始是全国，根据点的省市重绘这个图）

然后有个可以拖动的时间轴来explore地图上的时序信息？

**Comment by Ritaotao** [comment]
类似这个例子的[https://www.echartsjs.com/examples/zh/editor.html?c=area-simple](https://www.echartsjs.com/examples/zh/editor.html?c=area-simple)。 在省/市不同的粒度根据用户选择get数据来获取地方的时间信息。

也许可以做成通用组件？看起来前段也许会有一定需求。

**Comment by tongshuangwu** [comment]
duplicate #23
