### ISSUE TITLE
临时接口中的丁香园实时疫情接口疑似挂了

### ISSUE THREAD

**Issue by secsilm** [wuhan2020/map-viz#139]
接口：https://service-0gg71fu4-1252957949.gz.apigw.tencentcs.com/release/dingxiangyuan

不同 IP 均显示超限：

```json
{
    "message": "API rate limit exceeded"
}
```

**Comment by yarray** [comment]
这个接口没有用过吧，可以用 https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/json 这里的替代

**Comment by secsilm** [comment]
> 这个接口没有用过吧，可以用 https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/json 这里的替代

你这个也不错啊，话说有接口吗？

**Comment by yarray** [comment]
> > 这个接口没有用过吧，可以用 https://github.com/BlankerL/DXY-COVID-19-Data/tree/master/json 这里的替代
> 
> 你这个也不错啊，话说有接口吗？

可以直接请求 https://github.com/BlankerL/DXY-COVID-19-Data/raw/master/json/DXYArea.json 等
