### ISSUE TITLE
自动计算color scale

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#14]
现有的疫情地图是固定的color scale，因为有的省市人比较多有的比较少，写死color scale应该很快就会导致同色，自动算一下range然后做quartile binning应该会好一点？
code位置：[VirusMap](https://github.com/wuhan2020/map-viz/issues/23)

**Comment by lzxue** [comment]
自动计算会导致标准不一样

**Comment by tongshuangwu** [comment]
我也考虑了这个问题~但是还是想做一下，因为：
1. 固定scale的话，到市级很多城市color encoding会彻底没有意义。
2. 现在数据急速增长，很可能很快需要重新手写color encoding，我觉得很快会需要改代码不是很方便
3. quartile binning应该对于有些感染极高的outlier相对不那么敏感，不会像uniform binning一样把颜色拉的太远，应该最终是效果与现在相似

如果觉得#1不是一个大问题，也可以始终保持scale是按照省级计算，即使是显示不同省的城市的时候也不改动这个scale。

**Comment by shadowings-zy** [comment]
但是这样会不会造成一个误导？
比如说现在湖北省是黑的（感染人很多），云南省是黄的（感染人比较较少）。
然后点击到云南省查看省市详情，发现云南省感染人最多的市（可能也就感染了十几个人）也变成黑的了。
这样会不会给用户一种”哦原来云南省疫情也这么严重啊“的错觉？

**Comment by tongshuangwu** [comment]
写一个半自动的逻辑？
就是在全国的最大量算出来，然后算quartile，把最大值ceil到一个比较近的能整除500的数字。比如：
quartile最大值 = 2400
则
最上层 `>1000` ->  `> {2500}`，然后下面的值相应的缩放一下？

按照这个进展我们很快就得重新写一个手动color encoding了……

**Comment by yarray** [comment]
#95 实现了一个简单的策略：

以当前的分档（1,10,50,100,500,1000）与今日省数据最大值（5600+）为基准，对新的数据按省最大值对分档进行缩放，调整幅度最小为 500，市级数据采用同样的级别，不使用市级数据重新分级，以保持一致性。

暂时没有采用 quartile 因为我觉得对于有湖北这种超级 outlier 的数据不是很好（会出现多个与湖北同色的省，尽管相差十倍），我们也可以试试其它的 percentile 保证只留湖北一个，但是这种做法我也不太喜欢因为有糟糕的针对性... 归根结底好像考虑完整的分布而不只是 percentile 才是最完善的做法，我觉得我们慢慢想吧
