### ISSUE TITLE
3D地球可视化项目申请加入

### ISSUE THREAD

**Issue by hugetiny** [wuhan2020/map-viz#141]
3D地球可视化项目申请加入
github:
https://github.com/hugetiny/endofworld
效果：
https://endof.world/
我写了一个初步的项目，加入后仓库搬迁至wuhan2020

**Comment by zhaofeng-shu33** [comment]
Any documentations about your project? For example, how it is related with `wuhan2020`?

**Comment by tongshuangwu** [comment]
您好，
1. 这个repo只是wuhan2020的子项目，用于支撑他们首页的地图的。如果想要申请加入wuhan2020，大概得去https://github.com/wuhan2020/wuhan2020申请。
2. 我看了一下，很酷的3d效果！但是感觉要思考一下为什么需要立体效果？和平面地图比起来，这种可视化的优势是什么（当然我们地图是中国的，但是现在也有很多世界级的平面疫情地图）？而且我感觉现在好像交互还没完善，不能zoom-in或者显示是哪个国家什么的，感觉可以再开发一下~

**Comment by hugetiny** [comment]
数据的话wuhan2020貌似没有详细的带经纬度的全球数据，用的是CSSEGISandData/COVID-19的data
为什么要用立体效果的话 视觉冲击力吧，兼容性和可控性跟平面的没得比。不过兼容性我尽自己努力已经调到最优，像国内夸克浏览器这种直接砍掉webgl的就不可能支持了

**Comment by hugetiny** [comment]
如果可以整合的话 因为一样是echarts，可以考虑做渐进式的，浏览器支持就显示，不支持显示对应平面的。

**Comment by hugetiny** [comment]
@tongshuangwu 桌面浏览器鼠标滚轮可以缩放

**Comment by zhaofeng-shu33** [comment]
I find all code is put in `death.html` which is difficult for collaboration. Can you improve the code quality before others can contribute to your project?

**Comment by hugetiny** [comment]
@zhaifeng-shu33 有三个html 对应confirmed deaths recovered.没有用vue之类的框架。

**Comment by zhaofeng-shu33** [comment]
I know. At least JavaScript code should be put into separate files; and html and js code should be formatted.

**Comment by hugetiny** [comment]
已经清理好了

**Comment by zhaofeng-shu33** [comment]
OK

**Comment by lovepoem** [comment]
可以先看看 https://community.wuhan2020.org.cn/zh-cn/docs/dev/project-donate-guide.html
