### ISSUE TITLE
创建点图+map展示其他地理信息

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#15]
- **目的**：用于可视化各种不同地理信息（例如医院位置，酒店位置，etc.）
- **使用**：作为组件被前端调用，数据来自前端。
- **基础设计**：点图+地图-使用echarts+bmap，支持滚动缩放到具体坐标（[参考例子](https://www.echartsjs.com/examples/zh/editor.html?c=effectScatter-bmap)）
- **交互**：
  - 不自带过滤等交互组件，上层应该自己创建checkbox, slider, etc. 过滤后数据传入地图组件可以重绘地图
  - 接受传入的mouseEvent，可以帮助做信息过滤及定位（e.g., 点击一个省选中它的信息）
  - ([相关讨论](https://github.com/wuhan2020/map-viz/issues/2#issuecomment-578626578))

相关：
#3  input API
#5  创建医院/酒店等带地理位置的mockup数据
#2  点图实例

**Comment by tongshuangwu** [comment]
@shadowings-zy 朋友是不是在做这个？是的话可以assign一下自己！

**Comment by shadowings-zy** [comment]
可~这个交给我吧
/self-assign

**Comment by tongshuangwu** [comment]
pull request #24 ，已经merge

**Comment by tongshuangwu** [comment]
@shadowings-zy 朋友现在的组件是直接拿到mockup数据的，作为通用组件我们得给外面留个接口？
我新开了一个issue #29 ~
