### ISSUE TITLE
疫情地图接入时间信息+交互

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#23]
**目的&设计**：
创建一个独立的疫情地图可视化，有两个主要目标
1. 地理精度：有市级地理粒度，最开始是一个全国地图的heatmap，点击一个省重绘成省map。（[重绘参考](https://gallery.echartsjs.com/editor.html?c=xm3iS_cb0g)）
2. 时间信息：有时间轴，点击一个地区可以画出[stacked area chart](https://echarts.apache.org/examples/en/editor.html?c=area-stack)之类的疫情发展图 (确诊/疑似/死亡为不同层)，也可以根据选择的时间点重绘地图。([时间轴参考案例](https://echarts.apache.org/examples/en/editor.html?c=mix-timeline-finance))

**现状**：
疫情地图基础代码已经实现，请见[VirusMap]()
还需要：
- [ ] 添加时间信息
  - [x] 做时间轴 (见 #55 ，后续改善需求见 #57  )
  - [ ] 数据统计stacked area chart/line chart
- [x] 实现交互
  - [x] 点击省重绘省内地图/双击或提供按钮退出省内地图 (#47 #32 #27 )，
  - [x] 点击地图省市县同时重绘stacked area chart
  - [x] 点时间轴改变地图颜色

相关issue：
#22 现在的mockup数据不带时间信息，需要把API接入我们的代码，或者至少创建一个mock数据支持这部分的implementation

**Comment by tongshuangwu** [comment]
挪一下另一个issue下面的回复：
类似这个例子的https://www.echartsjs.com/examples/zh/editor.html?c=area-simple。 在省/市不同的粒度根据用户选择get数据来获取地方的时间信息。

也许可以做成通用组件？看起来前段也许会有一定需求。

cr: @Ritaotao

**Comment by YagiGo** [comment]
我可以尝试做一下省/市级别的stacked area chart和时间轴

**Comment by wmjpillow** [comment]
我可以帮忙做
点击省重绘省内地图/双击或提供按钮退出省内地图，同时重绘stacked area chart
 点时间轴改变地图颜色

**Comment by tongshuangwu** [comment]
谢谢两位，两位麻烦商量一下不要做重了？
另外数据 @yarray 已经接入了，请看 #27 
数据在https://github.com/wuhan2020/map-viz/tree/master/data

**Comment by tongshuangwu** [comment]
另外注意先pull一下上层哈，加了好多pull request，你们写的时候可能有conflict~

**Comment by YagiGo** [comment]
> 我可以帮忙做
> 点击省重绘省内地图/双击或提供按钮退出省内地图，同时重绘stacked area chart
> 点时间轴改变地图颜色

我做stacked area chart然后把做成独立组件，你做组件和现有地图的交互部分如何？

**Comment by tongshuangwu** [comment]
@YagiGo 他说在slack上联系你了！

**Comment by tongshuangwu** [comment]
@shadowings-zy 提供了一个web-cell的echarts封装可以支持两位的开发 #50

**Comment by tongshuangwu** [comment]
@yarray 现在把所有做这个的朋友都艾特进来了lol
大家可以尝试拆分小任务……

**Comment by yarray** [comment]
@tongshuangwu 我理解这个任务已经基本完事了...

**Comment by tongshuangwu** [comment]
说的有道理，我把这个issue关了，剩余需要做的包括线图和时间轴改善，分别在 #57 #58
