### ISSUE TITLE
通用组件需要接受外界发来的数据

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#29]
@shadowings-zy 朋友现在的组件是直接拿到mockup数据的，作为通用组件我们得给外面留个接口？
参照之前的数据设计讨论 #3 以及 @Ritaotao 创建的带地理数据的mockup #5

**Comment by shadowings-zy** [comment]
这个好说，我的BaiduMap.tsx已经留出了所有的配置参数，InformationMap.tsx只是做了一个取mock数据的操作。
如果现在mock数据已有，我就可以针对现有mock数据在InformationMap.tsx上再做一层封装。
这个我来弄吧。

**Comment by tongshuangwu** [comment]
蟹蟹！

**Comment by tongshuangwu** [comment]
其实我仍然没有懂这个map的api lol
这个object有点笼统，最好能展开写一下，就把现在mock数据的格式接入就可以：
```
interface InformationMapProps {
  options: Object
}
```
@yarray 如果对数据格式有想法的话也可以提~
或者明天我来改一下也可以~
