### ISSUE TITLE
把寻人/同行信息画到地图上（用百度地图插件）

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#33]
我忘了之前是哪位同学跟我说觉得这个会很有用，但是数据在这里……希望你能看到……
数据带有起始终止位置及时间，车序列号（不限高铁，也有公交车）
http://2019ncov.nosugartech.com/data.json

**Comment by nwljy** [comment]
这个接口还有飞机航班

**Comment by geastwood** [comment]
这是那里的数据？

**Comment by tongshuangwu** [comment]
就是那个寻人工具：http://2019ncov.nosugartech.com/
