### ISSUE TITLE
通过 Github Actions 实现 CI

### ISSUE THREAD

**Issue by WenheLI** [wuhan2020/map-viz#34]
对于这个可视化项目，我们可以直接将网页host在 Github Pages 上。
再加上 Actions 来实现自动CI，自动部署，这样也方便其他人直接查看这个可视化项目～

**Comment by tongshuangwu** [comment]
地图通用组件本来就是做给前端的，我们也木有数据自己host~
我感觉virus map也没有直接开一个页面的必要？就直接做在大项目下面其实会不那么分散？

**Comment by WenheLI** [comment]
我觉得现在这个 “组件” 体量已经蛮大的了
其实和一个独立的project差不多了 😂
完全可以用现有的 data api 做成一个完整的可视化项目？
（ 可能我现在的想法和整个项目思路不一样 hhh

**Comment by tongshuangwu** [comment]
是的，理论上来说疫情地图完全可以作为独立项目存在~但是一来已经有很多疫情地图存在了，我们的地图也没有突出到必须单独存在，二来如果因为主项目的主旨就是整合到一处，把疫情地图作为其中一个页面存在应该会更能实现整合目标 :)
