### ISSUE TITLE
志愿提供山东省137个县级区划的疫情追踪地图

### ISSUE THREAD

**Issue by wonke** [wuhan2020/map-viz#35]
根据国家卫健委关于疫情信息报告新要求，按病例确诊时医院所在县区统计。
本人基于地图慧工具创建并维护山东省区县级疫情地图，数据来源：山东省卫健委。
查看链接：https://g.dituhui.com/apps/range/viewMap/2c9085306fbb67f1016ff4a80b347e78
![批注 2020-01-30 132956](https://user-images.githubusercontent.com/32590930/73423314-bc1d8d80-4366-11ea-9a48-410dc44e0ca5.png)

**Comment by tongshuangwu** [comment]
您好~请问您数据是哪里扒来的呢~？

**Comment by wonke** [comment]
> 您好~请问您数据是哪里扒来的呢~？

你好，我制作的疫情地图数据来源是山东省卫健委官网，我省通告中提及:根据国家卫健委关于疫情信息报告新要求，按病例确诊时医院所在县区统计。但我浏览了几个省份的卫健委疫情通告，并未下探到县级。

**Comment by tongshuangwu** [comment]
如果您有兴趣提供数据的话可以和数据组联系
非常感谢，我们现在有一个新的issue做这个了 #52
