### ISSUE TITLE
地理精度要求能支持到 县级，甚至是乡镇级

### ISSUE THREAD

**Issue by jeffery9** [wuhan2020/map-viz#38]
如题，更精确追踪// 

另外 #39

**Comment by yarray** [comment]
绘制技术上可以支持，数据结构也可以兼容，但是现在没有稳定完整的数据源

**Comment by jeffery9** [comment]
今日头条有 县级的数据，先增加 按县级进行展示为好。

**Comment by tongshuangwu** [comment]
请问能给个数据api看一下是不是每天每个地方都有吗？
我们最开始确实想过做到县级，实在是没找到完整的数据~
#35 @wonke 也用县级数据画了图，如果有数据的话也希望能提供一下，我们再做安排~

**Comment by wonke** [comment]
你好，我制作的疫情地图数据来源是山东省卫健委官网，我省通告中提及:根据国家卫健委关于疫情信息报告新要求，按病例确诊时医院所在县区统计。但我浏览了几个省份的卫健委疫情通告，并未下探到县级。

**Comment by tongshuangwu** [comment]
非常感谢，我们现在有一个新的issue做这个了 #52

**Comment by ghost** [comment]
> 数据结构也可以兼容，但是现在没有稳定完整的数据源

有县级地图json数据吗？可以给我一份
