### ISSUE TITLE
增加自动更新 感染数据的功能

### ISSUE THREAD

**Issue by jeffery9** [wuhan2020/map-viz#39]

**Comment by jeffery9** [comment]
丁香园 API  http://lab.isaaclin.cn/nCoV/api/area?latest=0   无法访问了

**Comment by tongshuangwu** [comment]
为了防止对API造成太大的负担，现在是我们定时跑一下script从API拿一次数据存到本地。
而且可能为了支持区县级最终会变成手动收数据。
