### ISSUE TITLE
市级地图点legend会回到上层

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#42]
1. 因为市级数据不能点了，把hover上去的cursor改成普通？
2. 点legend会回上层，见图。现在我觉得现在市级地图好像点哪都是回上层……？能不能做个按键让只能点这里回上层？像这个里：https://gallery.echartsjs.com/editor.html?c=xm3iS_cb0g
![bug-click-legend](https://user-images.githubusercontent.com/6497707/73433767-3fed6080-42fa-11ea-994e-30b995207330.gif)

**Comment by yarray** [comment]
逻辑上是点空白才回到上层。市级数据点哪都回上层是因为没拦截 chart 的事件，或者也有可能哪里能 turn off clickable，我一会儿看一下吧。
