### ISSUE TITLE
之前没看到这个项目，我自己用高德地图做了一个简单的热力图

### ISSUE THREAD

**Issue by musistudio** [wuhan2020/map-viz#49]
之前没看到这个项目，我自己用高德地图做了一个简单的热力图，可以下钻到市级，数据写了个脚本可以实时更新，但考虑到服务器压力问题现在每天手动更新。地址http://wuhan.musiiot.top

**Comment by shadowings-zy** [comment]
您好，好像您链接中的疫情地图挂掉了诶……打开链接之后网页中只有地图🤦‍♂️

**Comment by musistudio** [comment]
> 您好，好像您链接中的疫情地图挂掉了诶……打开链接之后网页中只有地图🤦‍♂️

您刷新一下看看，可能刚好赶上我在更新数据

**Comment by tongshuangwu** [comment]
谢谢！我转到 #7 去了。
