### ISSUE TITLE
复查疫情地图市级时间序列数据

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#51]
搬运slack讨论
#48 @YagiGo 提到用省级时间加载在市级时间上，因为市级不是单独公布的，api里没有时间戳。
另外还需要做：
- [ ] 还要根据需要在国家级或者省级整理成 array，现在是嵌套的 (cr: @yarray )

之前的相关issue: #22 
如果做县级数据的相关issue: #52

**Comment by yarray** [comment]
这个已经弄好了，加了 Series<T> 泛型，issue 可以关了

**Comment by tongshuangwu** [comment]
朋友，我为你点赞o(￣▽￣)ｄ
