### ISSUE TITLE
明确化InformationMap的input interface

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#53]
现在[InformationMap.tsx](https://github.com/wuhan2020/map-viz/blob/master/source/components/InformationMap.tsx)收input的格式描述是:
```
interface InformationMapProps {
  options: Object
}
```
作为被人调用的通件我们需要更确切。根据现在调用的数据把`Object`扩写成实际接受的格式。

之前的相关issue是 #29

**Comment by shadowings-zy** [comment]
这个我来做好了，不过目前由于只有医院的信息，后续如果还有物资等信息的话，就需要再次进行修改。

**Comment by tongshuangwu** [comment]
我们和前端尝试保持一致吧？我看到水歌发的：
医疗物资数据结构 同步完了
https://github.com/wuhan2020/rest-api/commit/a15869c43920c61a2694d5995c6ae978642e843e
常用医疗物资的静态数据也有了
https://github.com/wuhan2020/wuhan2020.github.io/commit/dafa0608b291e3b21fa478ea32c1372b8785f46d
物流公司数据模型
https://github.com/wuhan2020/rest-api/blob/master/source/model/Logistics.ts
宾馆数据结构
https://github.com/wuhan2020/rest-api/blob/master/source/model/Hotel.ts

**Comment by tongshuangwu** [comment]
@shadowings-zy

**Comment by shadowings-zy** [comment]
我看了一下水歌的数据格式，能显示在地图上的只有医院信息和宾馆信息。
其他的信息因为没有经纬度所以显示不了。
所以我们的GeoData中的type应该只有"hospital"|"hotel"，
最后格式大概是这样子：
`
interface GeoData {
  type: "hospital"|"hotel"
  name: string,
  coord: [number, number],
  metadata: {
    key: string, 
    value: string, 
    url?:  string 
  }
}
`

label的text和style可以咨询设计之后固定下来。
这样我觉得就ok了。

**Comment by tongshuangwu** [comment]
我去问一下design以及确认一下是不是只有这两个需要做地图信息~

**Comment by tongshuangwu** [comment]
我看了一下，那个metadata还是得给他们定一下格式的，要么就做医院和酒店两个interface，要么就写一个尽可能general的然后接受他们自己加别的option。这个我来看一下吧~
