### ISSUE TITLE
重构使用react

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#54]
要改为react了。

**Comment by shadowings-zy** [comment]
重构成react很快，没太多问题。
重构成vue需要改动的代码会多一些。
但是就目前的代码体量来看，都是能在一天之内搞定的。
等我们先做完这个组件给前端用上了，再开启这个工作吧。

**Comment by tongshuangwu** [comment]
同意🙆

**Comment by shadowings-zy** [comment]
已重构完成，代码放到了react分支下。
不过需要更新一下文档。
