### ISSUE TITLE
基础线图implementation + 改善

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#58]
#50  已经添加了一个基础折线图。下面要做：

- [x] 纵轴加标签
- [x] 做成可以区分 确诊-疑似-死亡-治愈：确认+疑似做[stacked bar chart](https://www.echartsjs.com/examples/zh/editor.html?c=area-stack)方便辨认总数和趋势，死亡+治愈做[折线图](https://www.echartsjs.com/examples/zh/editor.html?c=line-marker)方便辨认分别的趋势。
- [ ] 两个图上下对准统一放在地图左侧/右侧
- [ ] 交互：点击时间轴的时候在线图上highlight出时间点

原issue: #23 因为已经做了大部分，把线图单独拆成一个issue。

**Comment by tongshuangwu** [comment]
@yarray @shadowings-zy @yarray 这个

**Comment by shadowings-zy** [comment]
我的建议是做多个折线图，疑似+确诊做一个折线图（也可以是stacked line chart），治愈+死亡做一个折线图。
因为把治愈+确诊+治愈+死亡做成一个stacked bar chart没意义啊，它们四个的类型都不一样。
最多是治愈+确诊能做成一个stacked bar chart。治愈和死亡放到一起没意义= =

**Comment by tongshuangwu** [comment]
我之前是觉得疑似不是单调递增的，疑似的变成确诊之后量会下降，有点诡异，叠加的话能看到一共有多少人被影响了。
但是你说得对，全部stack好像问题更大，治愈+死亡+确诊很多人被重复算了。
两个折线图会不会有点太多图了？只要能开关每个线，他们都在一起应该就可以？

**Comment by shadowings-zy** [comment]
我想要分成两张图的原因是，治愈/死亡和疑似/确诊根本不在一个数量级上。
如果放到一张图，治愈/死亡这两条线基本就是横躺在x轴上，效果很不好（我最开始关注这个项目的时候就做了这部分的工作，四条线放到同一张图里效果很差）

虽然echarts支持开关每一条线，但是在移动端，我个人觉得那个开关的交互不是很友好，因为icon太小了，而且如果“让用户先关掉两条线才能查看到治愈/死亡数”，这样的交互方式对用户来说也不是很好，这增大了用户触达他们想要的数据的难度。

**Comment by tongshuangwu** [comment]
@shadowings-zy 根据讨论更新了issue描述！

**Comment by shadowings-zy** [comment]
本功能已开发完成并且merge到主分支了。

备注1：
两个图上下对准统一放在地图左侧/右侧：此feature由于在手机端显示不佳，所以将两个图上下对准放到了地图下方。

备注2：
点击时间轴的时候在线图上highlight出时间点：此feature需要和 @yarray 进一步讨论组件参数。

**Comment by tongshuangwu** [comment]
根据与其他问题的相关性重新开了 #72 和 #73 。
