### ISSUE TITLE
地图可视化技术方案可以采用L7

### ISSUE THREAD

**Issue by lzxue** [wuhan2020/map-viz#6]
疫情地图
https://github.com/lzxue/yiqingditu 

可视化库
https://github.com/antvis/L7

**Comment by tongshuangwu** [comment]
感谢提议！
我们已经在用echarts进行开发了，它对map visualization的支持足够我们用了。例子可以见 #2 
现在这个库的主要目的是做一个相对通用的地图组件给前端，不光是疫情信息，也尽量可以展示医院需求、物流工厂、酒店等的地理信息，最好可以做精细化展示和地理信息的范围查询能力。
如果感兴趣参与更多讨论，欢迎加入[Slack 交流群组](https://join.slack.com/t/wuhan2020/shared_invite/enQtOTIzNjA2MDYwOTUxLWVjMjA4MjdhNGVmZmZlZTgxYjM1ZDY1NGVkZDVkNGI0NzhjZGVlYTM2Mjc5Mjk2YjgyYTk1NDJmNTkxODZlOTE)，我们在 `#map-visualization` channel
