### ISSUE TITLE
疫情地图返回上级的按钮太不起眼了lol

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#72]
左下那个返回上一级的小按钮有点不起眼，挪到别的地方（并且label一下现在在那个省里？）
![image](https://user-images.githubusercontent.com/6497707/73560606-20465d00-440c-11ea-91b5-a6c5d3cfa1dd.png)

**Comment by tongshuangwu** [comment]
@yarray @shadowings-zy

**Comment by shadowings-zy** [comment]
这个我已经在我的新PR里解决了，提供电脑端手机端两种不同的适配方案

电脑端是地图在左边，两张折线图纵向排列在右面
手机端是地图和折线图纵向排列

**Comment by tongshuangwu** [comment]
然而那个不起眼的小按钮还是没能解决~

**Comment by yarray** [comment]
那个小按钮主要是给移动端用的，桌面端双击就返回上级了，所以没太管位置。
改到右下 legend 下面是不是好些？
