### ISSUE TITLE
疫情地图用大数字写出总数

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#85]
- [ ] designer给我的design。可以考虑加在地图或者线图上面？
<img width="587" alt="Screen Shot 2020-01-31 at 11 30 47 AM" src="https://user-images.githubusercontent.com/6497707/73589478-9f2eaa80-448b-11ea-8c07-c51f5a4c0972.png">

**Comment by Hedgeh09** [comment]
可以通过折线图显示当前浏览省市
<img width="1369" alt="截屏2020-02-01下午8 56 33" src="https://user-images.githubusercontent.com/38356240/73592611-2dac3600-4537-11ea-9f63-f6f11331649b.png">

**Comment by Hedgeh09** [comment]
设计组方案有更新，先沟通下再进行。
<img width="336" alt="截屏2020-02-02下午4 01 52" src="https://user-images.githubusercontent.com/38356240/73605362-3e60b880-45d8-11ea-8bba-409d916b3f0b.png">

**Comment by tongshuangwu** [comment]
前端去写了~
