### ISSUE TITLE
VirusMap 默认显示省市名字label

### ISSUE THREAD

**Issue by tongshuangwu** [wuhan2020/map-viz#9]
现在是默认完全无label的状态，感觉有点太难找了XD

**Comment by shadowings-zy** [comment]
emm，你是说直接在每个省市上面添加地名是嘛……这个我试过，如果遇到一些面积比较小的区域（比如北京，天津等，尤其是在手机端）字密密麻麻的很不好看，如下图：
<img width="319" alt="截屏2020-01-28上午10 46 06" src="https://user-images.githubusercontent.com/29225966/73231461-65c01b80-41bb-11ea-9965-6266cf77863e.png">

**Comment by tongshuangwu** [comment]
就是把字做小一点？
或者加上缩放（[这个](https://gallery.echartsjs.com/editor.html?c=xm3iS_cb0g)或[这个](https://www.echartsjs.com/examples/zh/editor.html?c=effectScatter-bmap)），缩放到一定程度以后就显示字？
因为感觉大部分现在有的疫情地图也都会加字~ 比如这里的这些 #7

**Comment by shadowings-zy** [comment]
行，这个issue我来完善
