### ISSUE TITLE
移动端两个折线图被百度地图遮挡，部分窄屏机型图例会消失

### ISSUE THREAD

**Issue by Hedgeh09** [wuhan2020/map-viz#94]
1，移动端两个折线图被百度地图遮挡
<img width="497" alt="截屏2020-02-01下午10 41 50" src="https://user-images.githubusercontent.com/38356240/73594284-e37f8080-4547-11ea-9fe0-cc0551d8c8cb.png">
2，部分窄屏机型图例会消失
<img width="957" alt="截屏2020-02-01下午10 46 48" src="https://user-images.githubusercontent.com/38356240/73594289-f003d900-4547-11ea-9bfc-4dca2a93fa3d.png">

**Comment by shadowings-zy** [comment]
针对第一个问题：
折线图会被地图盖住是css的问题，但是实际上MapViz组件只是用来展示组件用法以及方便我们调试的，所以我们没有针对这两个组件写样式，只是单纯把他们俩叠到了一起。真正在使用的时候不会出现这个问题（因为这两个组件根本不会像这样放到一起）

如果我们需要使用疫情地图组件，就直接用 
<HierarchicalVirusMap data={data} resolution={resolution} />
即可

如果我们要使用通用地图组件，直接使用
          <InformationMap
            initPoint={informationMockData.initPoint}
            zoom={informationMockData.zoom}
            markers={informationMockData.makerArray} />
即可
`     
 <div>
        <div style={{ width: '100%', height: '100%' }}>
          <HierarchicalVirusMap data={data} resolution={resolution} />
        </div>
        <div style={{ width: '100%', height: '80%' }}>
          <InformationMap
            initPoint={informationMockData.initPoint}
            zoom={informationMockData.zoom}
            markers={informationMockData.makerArray} />
        </div>
      </div>
`

**Comment by tongshuangwu** [comment]
这个之前是特意把它去掉了觉得挡了地图。加回来了。
